### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Ika-Taro** [Ika-Taro/furima-37499#22]
# フリマアプリのURL
- https://furima-37499.herokuapp.com/

# Basic認証のIDとパスワード
- ID: taro
- Password: 0402

# 出品者用のメールアドレスとパスワード
- Email: test@com
- Password: aa123456789

# 購入者用のメールアドレスとパスワード
- Email: test@aaaa
- Password: aa123456789

**Comment by shodai-ito** [comment]
@Ika-Taro さん、ご提出ありがとうございます‼︎
動作の確認をしようとしましたが、添付いただいているアプリのURLがherokuサイトのものとなっており、アプリの確認ができませんでした。
herokuにデプロイしたアプリのURLを再度添付お願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Ika-Taro** [comment]
> @Ika-Taro さん、ご提出ありがとうございます‼︎ 動作の確認をしようとしましたが、添付いただいているアプリのURLがherokuサイトのものとなっており、アプリの確認ができませんでした。 herokuにデプロイしたアプリのURLを再度添付お願いいたします。
> 
> 修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！ ※新しいissueを作っていただく必要はございません。 ※質問等でコメントした場合も都度フォームのご提出をお願いします。 https://forms.gle/dYuR1wjeHepbEhU7A

失礼いたしました。
URL更新いたしました。
よろしくお願いいたします。

**Comment by shodai-ito** [comment]
@Ika-Taro さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **発送までの日数は、「---、1〜2日で発送、2〜3日で発送、4〜7日で発送」の4項目が表示されること（--- は初期値として設定すること）**
<img width="844" alt="スクリーンショット 2022-03-02 11 19 57" src="https://user-images.githubusercontent.com/62537107/156286172-26944345-e093-4ba0-a47c-f4bbadb59810.png">
日数表示が一部崩れてしまっております。


- [x] **ログアウト状態の場合は、商品購入ページに遷移しようとすると、商品の販売状況に関わらずログインページに遷移すること**
<img width="720" alt="スクリーンショット 2022-03-02 11 55 27" src="https://user-images.githubusercontent.com/62537107/156286184-b4ece1bd-4dcc-4bec-bc78-78ddd7cf7da6.png">
エラー画面になってしまいます。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shodai-ito** [comment]
@Ika-Taro さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
